# Base configs
url: "https://vi-gr.github.io"
baseurl: "/photography"

image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography ~ Alternative Processes ~ Videography"
subtitle: "Alternative processes Photography  Videography"
author: "Dame Sinclair"
header:
 title: "Images"
 subtitle: "by Dame Sinclair"
footer:
 name: "The process"
 bio: "I am a photographer and videographer living in Brooklyn. My explorations are a side effect of my curiosity and deep enjoyment of the art and science of photography. This gallery is composed by cyanotypes on glass, digital pictures, film scans and platinum prints. Click on my photo below to visit my Flickr page."
 

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
 
  instagram: "https://www.instagram.com/damesinclair?igsh=NmUza214aHF5ZjV5&utm_source=qr"

